# Generated by Django 3.0.3 on 2020-02-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('hu', 'Hungarian'), ('de', 'German')], default='en', help_text='Book language', max_length=2),
        ),
    ]
